apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: e2e
  template:
    metadata:
      labels:
        app.kubernetes.io/name: e2e
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: e2e
          image: {{ .Values.e2e.image }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: mongodb
